GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/628c4e262e150663455b0b67

###
POST https://salty-hamlet-24205.herokuapp.com/api/notes
Content-Type: application/json

{
  "content": "Hi",
  "important": false
}

###
PUT http://localhost:3001/api/notes/628ea6768ae428f54d11c35e
Content-Type: application/json

{
  "content": "Upd",
  "important": true
}

