GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/628ea6768ae428f54d11c35e

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer xxxxx

{
  "content": "Hi1234",
  "important": false
}

###
PUT http://localhost:3001/api/notes/628ea6768ae428f54d11c35e
Content-Type: application/json

{
  "content": "Up3d",
  "important": true
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "username": "root2233334",
  "name": "Superuser2323343",
  "password": "salainen"
}

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "salainen"
}