POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2RmMzVmMDE0MjQwYmM0MzM5OGE5YyIsInVzZXJuYW1lIjoic2FtdWVsIiwiaWF0IjoxNjU3NjY0MzU1LCJleHAiOjE2NTc2ODIzNTV9.vS4HiQHLlIpsMlz1oxL_mmmI_XFLoM2g7MOmwXQEato"

{
  "title": "12345",
  "author": "1234",
  "url": "gg"
}

###
GET http://localhost:3003/api/blogs/

###
PUT http://localhost:3003/api/blogs/62cdf39c014240bc43398aa3
Content-Type: application/json

{
  "author": "Daniel 2",
  "title": "Updated Title",
  "url": "www.yahoo.com",
  "likes": 3
}

###
DELETE http://localhost:3003/api/blogs/62cdea41ff7b50788884062b
Authorization: bearer 

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "samuel",
  "name": "sam",
  "password": "qw1234"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "samuel",
  "password":"qw1234"
}