POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Blog title",
  "author": "Daniel",
  "url": "www.google.com",
  "likes": 5
}

###
GET http://localhost:3003/api/blogs/

###
PUT http://localhost:3003/api/blogs/629fd808c3632d3cd93828fe
Content-Type: application/json

{
  "author": "Daniel 2",
  "title": "Updated Title",
  "url": "www.yahoo.com",
  "likes": 3
}

###
DELETE http://localhost:3003/api/blogs/629fd80fc3632d3cd9382900